version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
      
    working_directory: ~/ppl

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: 
          name: Test
          command: yarn test

      - run:
          name: Deploy
          command: curl -X POST -d '' https://api.netlify.com/build_hooks/5bce6665dd28ef6e71af5c86
