backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow
display_url: https://pulsarpremierleague.com

collections:
  - name: "news"
    label: "News"
    label_singular: "Post"
    folder: "static/data/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Image", name: "cover", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "select", options: ["Event", "Interview", "News", "Players", "Review", "Teams", "Video"]}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      
      - file: "static/data/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-post"}
          - {label: "Hero", name: "hero", widget: "object",
              fields: [
                {label: "Title", name: "title", widget: "string"}, 
                {label: "Subtitle", name: "subtitle", widget: "string"},
                {label: "Image", name: "img", widget: "image"}
              ]
            }
          - {label: "About", name: "tabs", widget: "list", 
              fields: [
                {label: "Name", name: "name", widget: "string"},
                {label: "Description", name: "description", widget: "markdown"}
              ]
            }
          - {label: "Sponsors", name: "sponsors", widget: "list", 
              fields: [
                {label: "Name", name: "name", widget: "string"},
                {label: "Description", name: "description", widget: "text", required: false},
                {label: "Link", name: "link", widget: "string"},
                {label: "Image", name: "img", widget: "image"}
              ]
            }

  - name: Site
    label: Site
    files:
      
      - file: static/data/site/config.json
        label: Config
        name: config
        fields: 
          - {label: URL, name: url, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Alternate, name: alternate, widget: string, required: false}
          - {label: Description, name: description, widget: string}
          - {label: Copyright, name: copyright, widget: hidden}
          # - {label: Logo, name: logo, widget: image}
          - {label: Favicon, name: favicon, widget: hidden, required: false}
          - {label: Social, name: social, widget: object, 
              fields: [
                {label: Discord, name: discord, widget: string, required: false},
                # {label: GitHub, name: github, widget: hidden, required: false},
                # {label: LinkedIn, name: linkedin, widget: hidden, required: false},
                {label: Twitch, name: twitch, widget: string, required: false},
                {label: Twitter, name: twitter, widget: string, required: false},
                {label: YouTube, name: youtube, widget: string, required: false}
              ]
            }
          - {label: Google Analytics ID, name: googleAnalyticsId, widget: string}
          - {label: Path Prefix, name: pathPrefix, widget: hidden}
          - {label: RSS, name: rss, widget: hidden}
